# Generated by Django 3.2.12 on 2022-03-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200518_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='Not Found', max_length=1000, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(default='Not Found', max_length=1000, null=True)),
            ],
        ),
    ]
