# Generated by Django 3.2.12 on 2022-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='password1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password2',
            field=models.CharField(max_length=20),
        ),
    ]
